export const abusiveWord = [
    "Madarchod",
    "Madarchood",
    "Madarchoodd",
    "Bitch",
    "Chutiya",
    "Bhosadike",
    "Bhosda",
    "Bhosde",
    "Bhosdike",
    "Fuck",
    "Motherfucker",
    "TMC",
    "ass",
    "asshole",
    "gaand mara",
    "Gandu",
    "bhenchod",
    "bc",
    "mc",
    "chutmarike",
    "chut",
    "Bastard",
    "chutiyapa"
]